name: cinebox
description: "Demo project ramon.pt"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  envied: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  riverpod_generator: ^3.0.0-dev.17
  build_runner: ^2.5.4
  envied_generator: ^1.2.0

flutter:
  uses-material-design: true
